
name: Automate Issue Creation2
on: [workflow_dispatch]
#  schedule:
#    - cron: '0 7 * * *'

jobs:
  check_release:
    name: Check For Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    
    #get notifications data (defaults to unread notifications only)
      - name: Get Notification Data
        run: |
          resp=$(curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.NOTIFICATION_CHECKER }}" \
          https://api.github.com/notifications)
          
    #check for release within target repository
    #if a release is found, create and issue and mark notification as read

      - name: Check Notification
        id: notif-check
        shell: bash
        run: |

          for row in $(echo "${resp}" | jq -r '.[] | @base64'); do
              type=$(echo ${row} | base64 --decode | jq -r '.subject.type' )
              repo=$(echo ${row} | base64 --decode | jq -r '.repository.full_name' )

              if [[ $type == "Release" ]] && [[ $repo == "ibm-mas/ansible-devops" ]]; then

                  title=$(echo ${row} | base64 --decode | jq -r '.subject.title' )
                  threadid=$(echo ${row} | base64 --decode | jq -r '.id' )

                # generate issue data for the curl to create an issue
                  _issue_data()
                  {
                      cat << EOF
          {
              "title": "New $repo Release: $title",
              "body": "New Release $title created in $repo",
              "labels": [
                  "enhancement",
                  "new release"
              ]
          }
          EOF
                  }

                  # create the issue using the issue data function
                  curl -X "POST" "https://api.github.com/repos/tcskill/mas-issue-automation/issues" \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.NOTIFICATION_CHECKER }}" \
                  -d "$(_issue_data)"

                  # mark the notification as read so we don't create duplicate issues
                  curl -X PATCH \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.NOTIFICATION_CHECKER }}" \
                  https://api.github.com/notifications/threads/${threadid}

              fi
              
          done
