
name: Automate Issue Creation2
on: [workflow_dispatch]
#  schedule:
#    - cron: '0 7 * * *'

jobs:
  check_release:
    name: Check For Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    
    #get notifications data (defaults to unread notifications only)
      - name: Get Notification Data
        run: |
          resp=$(curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.NOTIFICATION_CHECKER }}" \
          https://api.github.com/notifications)
          
    #check for release within target repository
    #if a release is found, create and issue and mark notification as read

      - name: Check Notification
        id: notif-check
        shell: bash
        run: |

         for row in $(echo "$resp" | jq -c '. | map(.) | .[]'); do
            echo "new row: ${row}"
            _jq() {
            echo ${row} | jq -r "${1}"
            }
          echo $(_jq '.[].subject.type') "=" $(_jq '.[].repository.full_name')
         done

#         for (( i=0; i<$length; i++ )); do
#            type=$(echo "$resp" | jq '.[$i].subject.type')
#            echo $i
#            echo $type
#
#         done         