
name: Automate Issue Creation2
on: [workflow_dispatch]
#  schedule:
#    - cron: '0 7 * * *'

jobs:
  check_release:
    name: Check For Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
  
    #check for release within target repository
    #if a release is found, create and issue and mark notification as read

      - name: Check Notifications
        id: notif-check
        #shell: bash
        run: ./.github/workflows/scripts/createIssues.sh
